"""
FSANZ Standard 2.9.4 & Schedule 29 Computational Engine
Implements multi-ingredient elemental aggregation, molar concentration gatekeeping,
non-ideal osmolality modeling, and ReportLab PDF specification rendering.
"""

import streamlit as st
import pandas as pd
from io import BytesIO
from dataclasses import dataclass
from typing import List, Dict, Any, Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas

from engines.base_engine import BaseComputationalEngine

# =====================================================================
# 1. FSANZ REGULATORY CONSTANTS & THRESHOLDS
# =====================================================================

FSANZ_SCHEDULE_29_LIMITS = {
    "Sodium": {"min_daily": 210.0, "max_daily": 520.0, "unit": "mg"},
    "Potassium": {"min_daily": 130.0, "max_daily": 1300.0, "unit": "mg"},
    "Magnesium": {"min_daily": None, "max_daily": 320.0, "unit": "mg"},
    "Vitamin C": {"min_daily": None, "max_daily": 100.0, "unit": "mg"},
    "Caffeine": {"min_daily": None, "max_daily": 100.0, "max_serve": 80.0, "unit": "mg"}
}

# Standard 2.9.4 Div 2 Sodium Molar Limits for Electrolyte Drinks (mmol/L)
STD_294_SODIUM_MIN_MMOL_L = 10.0
STD_294_SODIUM_MAX_MMOL_L = 30.0
SODIUM_ATOMIC_WEIGHT = 22.990

MANDATORY_WARNINGS = {
    "caffeine": "Contains caffeine. Not recommended for children, pregnant or lactating women, or individuals sensitive to caffeine.",
    "sports_gen": "Not suitable for children under 15 years of age or pregnant women: Should only be used under medical or dietetic supervision.",
    "consumption": "Should be consumed in conjunction with a nutritious diet and an appropriate physical training or exercise program."
}

# =====================================================================
# 2. DATA STRUCTURES
# =====================================================================

@dataclass
class FormulaIngredient:
    name: str
    amount_per_serve_mg: float
    active_compound: str
    active_yield_pct: float
    mw: float
    van_thoff: int

# =====================================================================
# 3. REPORTLAB PDF CANVAS & SPECIFICATION BUILDER
# =====================================================================

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas for dynamic page numbering and running headers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#1A365D"))
        
        # Header
        self.drawString(36, 762, "FSANZ STANDARD 2.9.4 REGULATORY COMPLIANCE DOSSIER")
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        self.drawRightString(576, 762, "CONFIDENTIAL / FORMULATION AUDIT")
        
        self.setStrokeColor(colors.HexColor("#CBD5E0"))
        self.setLineWidth(0.5)
        self.line(36, 754, 576, 754)
        
        # Footer
        self.line(36, 45, 576, 45)
        self.setFont("Helvetica", 8)
        self.drawString(36, 32, "Generated by In-Silico FSANZ Regulatory Audit Engine")
        self.drawRightString(576, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def build_factory_spec_pdf(res: Dict[str, Any]) -> BytesIO:
    """Generates an enterprise-ready PDF specification dossier from audit results."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#1A365D")
    )
    h2_style = ParagraphStyle(
        "SectionH2",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#2B6CB0"),
        spaceBefore=10,
        spaceAfter=4
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#2D3748")
    )
    warn_style = ParagraphStyle(
        "WarnText",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#C53030")
    )

    story = []

    # Title Banner
    story.append(Paragraph(f"Factory Specification: {res['product_name']}", title_style))
    story.append(Paragraph(f"<b>Variant / Flavor:</b> {res['flavor']} | <b>Net Weight:</b> {res['stick_weight_g']}g | <b>Serves/Day:</b> {res['serves_per_day']}", body_style))
    story.append(Spacer(1, 10))

    # Executive Verdict Box
    verdict_color = colors.HexColor("#2F855A") if "PASS" in res["overall_status"] else colors.HexColor("#C53030")
    verdict_text = f"<b>FSANZ AUDIT VERDICT: {res['overall_status']}</b>"
    
    verdict_table = Table(
        [[Paragraph(verdict_text, ParagraphStyle("VerdictStyle", parent=body_style, fontName="Helvetica-Bold", fontSize=11, textColor=colors.white))]],
        colWidths=[540]
    )
    verdict_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), verdict_color),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(verdict_table)
    story.append(Spacer(1, 12))

    # Key Biophysical Metrics
    story.append(Paragraph("1. Physical & Molar Solution Metrics", h2_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=8))
    
    metrics_data = [
        ["Metric Parameter", "Calculated Value", "Regulatory Standard Target"],
        ["Prepared Solution Osmolality", f"{res['osmolality_mOsm_kg']} mOsm/kg", "270 - 330 mOsm/kg (Isotonic target)"],
        ["Hydration Classification", res['osmo_classification'], "Standard 2.9.4 Division 2"],
        ["Sodium Molar Concentration", f"{res['sodium_mmol_l']:.2f} mmol/L", "10.0 - 30.0 mmol/L (Mandatory)"],
    ]
    
    t_metrics = Table(metrics_data, colWidths=[180, 160, 200])
    t_metrics.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EDF2F7")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#1A365D")),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(t_metrics)
    story.append(Spacer(1, 12))

    # Audit Table
    story.append(Paragraph("2. Schedule 29 Active Ingredient Audit Matrix", h2_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=8))

    table_headers = ["Compound", "Per Serve", "Daily Intake", "Regulatory Limit", "Status", "Audit Findings"]
    table_rows = [[Paragraph(f"<b>{h}</b>", body_style) for h in table_headers]]

    for row in res["audit_table"]:
        status_color = "#2F855A" if row["Status"] == "PASS" else ("#DD6B20" if row["Status"] == "WARNING" else "#C53030")
        table_rows.append([
            Paragraph(row["Compound"], body_style),
            Paragraph(row["Per Serve"], body_style),
            Paragraph(row["Daily Intake"], body_style),
            Paragraph(row["Regulatory Limit"], body_style),
            Paragraph(f"<font color='{status_color}'><b>{row['Status']}</b></font>", body_style),
            Paragraph(row["Details"], body_style)
        ])

    t_audit = Table(table_rows, colWidths=[80, 65, 65, 100, 60, 170])
    t_audit.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#EDF2F7")),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(t_audit)
    story.append(Spacer(1, 12))

    # Mandatory Warnings
    story.append(Paragraph("3. Mandatory Packaging Label Statements", h2_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0"), spaceAfter=8))
    for warn in res["mandatory_warnings"]:
        story.append(Paragraph(f"• {warn}", warn_style))
        story.append(Spacer(1, 3))

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer

# =====================================================================
# 4. PRIMARY MATHEMATICAL COMPUTATIONAL ENGINE
# =====================================================================

class FSANZ294Engine(BaseComputationalEngine):
    @property
    def engine_id(self) -> str:
        return "fsanz_294_sports_drink"

    @property
    def engine_name(self) -> str:
        return "FSANZ Standard 2.9.4 Sports Drink Auditor"

    @property
    def domain_category(self) -> str:
        return "Food Science & Oral Nutraceuticals"

    def render_inputs(self, st_ctx: Any) -> Dict[str, Any]:
        st_ctx.subheader("Product Parameters")
        product_name = st_ctx.text_input("Product Name", "Hydration Electrolyte Powder")
        flavor = st_ctx.text_input("Flavor Variant", "Lemon Lime")
        stick_weight = st_ctx.number_input("Stick Pack Net Weight (g)", min_value=1.0, max_value=50.0, value=7.5, step=0.1)
        serves_day = int(st_ctx.number_input("Max Daily Servings", min_value=1, max_value=6, value=2, step=1))
        dilution_ml = st_ctx.number_input("Dilution Volume per Serve (mL Water)", min_value=100.0, max_value=2000.0, value=500.0, step=50.0)

        st_ctx.markdown("#### Formula Active Raw Ingredients (mg/serve)")
        sod_citrate = st_ctx.number_input("Sodium Citrate Dihydrate (mg)", min_value=0.0, value=1000.0, step=50.0)
        sod_chloride = st_ctx.number_input("Sodium Chloride (mg)", min_value=0.0, value=250.0, step=25.0)
        pot_chloride = st_ctx.number_input("Potassium Chloride (mg)", min_value=0.0, value=300.0, step=25.0)
        mag_glycinate = st_ctx.number_input("Magnesium Glycinate (mg)", min_value=0.0, value=400.0, step=25.0)
        vit_c = st_ctx.number_input("Ascorbic Acid / Vitamin C (mg)", min_value=0.0, value=45.0, step=5.0)
        caffeine = st_ctx.number_input("Natural Caffeine (mg)", min_value=0.0, value=35.0, step=5.0)

        ingredients = [
            FormulaIngredient("Sodium Citrate Dihydrate", sod_citrate, "Sodium", 23.45, 294.10, 4),
            FormulaIngredient("Sodium Chloride", sod_chloride, "Sodium", 39.34, 58.44, 2),
            FormulaIngredient("Potassium Chloride", pot_chloride, "Potassium", 52.45, 74.55, 2),
            FormulaIngredient("Magnesium Glycinate", mag_glycinate, "Magnesium", 14.10, 172.42, 1),
            FormulaIngredient("Ascorbic Acid", vit_c, "Vitamin C", 100.00, 176.12, 1),
            FormulaIngredient("Natural Caffeine", caffeine, "Caffeine", 100.00, 194.19, 1),
        ]

        return {
            "product_name": product_name,
            "flavor": flavor,
            "stick_weight": stick_weight,
            "serves_day": serves_day,
            "dilution_ml": dilution_ml,
            "ingredients": ingredients
        }

    def execute(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        serves = max(1, int(inputs["serves_day"]))
        dilution_l = max(inputs["dilution_ml"], 1.0) / 1000.0
        
        aggregated_serve: Dict[str, float] = {}
        aggregated_daily: Dict[str, float] = {}
        
        # 1. Precise Multi-Ingredient Elemental Mass Aggregation
        for ing in inputs["ingredients"]:
            active_serve = ing.amount_per_serve_mg * (ing.active_yield_pct / 100.0)
            active_daily = active_serve * serves
            
            aggregated_serve[ing.active_compound] = aggregated_serve.get(ing.active_compound, 0.0) + active_serve
            aggregated_daily[ing.active_compound] = aggregated_daily.get(ing.active_compound, 0.0) + active_daily

        # 2. Standard 2.9.4 Prepared Sodium Concentration (mmol/L)
        sodium_serve_mg = aggregated_serve.get("Sodium", 0.0)
        sodium_mmol_l = (sodium_serve_mg / SODIUM_ATOMIC_WEIGHT) / dilution_l

        audit_table = []
        overall_status = "PASS"
        warnings = set()
        warnings.add(MANDATORY_WARNINGS["sports_gen"])
        warnings.add(MANDATORY_WARNINGS["consumption"])

        # Check Sodium Molar Target under Standard 2.9.4 Div 2
        if sodium_serve_mg > 0:
            if sodium_mmol_l < STD_294_SODIUM_MIN_MMOL_L:
                overall_status = "FAIL" if overall_status != "FAIL" else "FAIL"
                audit_table.append({
                    "Compound": "Sodium (Concentration)",
                    "Per Serve": f"{sodium_mmol_l:.2f} mmol/L",
                    "Daily Intake": f"{sodium_mmol_l * serves:.2f} mmol/L",
                    "Regulatory Limit": f"{STD_294_SODIUM_MIN_MMOL_L} - {STD_294_SODIUM_MAX_MMOL_L} mmol/L",
                    "Status": "FAIL",
                    "Details": f"Below min FSANZ electrolyte drink concentration ({STD_294_SODIUM_MIN_MMOL_L} mmol/L)."
                })
            elif sodium_mmol_l > STD_294_SODIUM_MAX_MMOL_L:
                overall_status = "FAIL"
                audit_table.append({
                    "Compound": "Sodium (Concentration)",
                    "Per Serve": f"{sodium_mmol_l:.2f} mmol/L",
                    "Daily Intake": f"{sodium_mmol_l * serves:.2f} mmol/L",
                    "Regulatory Limit": f"{STD_294_SODIUM_MIN_MMOL_L} - {STD_294_SODIUM_MAX_MMOL_L} mmol/L",
                    "Status": "FAIL",
                    "Details": f"Exceeds max FSANZ electrolyte drink concentration ({STD_294_SODIUM_MAX_MMOL_L} mmol/L)."
                })

        # 3. Schedule 29 Daily Caps & Single Serve Limits
        for compound, daily_val in aggregated_daily.items():
            serve_val = aggregated_serve[compound]
            limits = FSANZ_SCHEDULE_29_LIMITS.get(compound, {})
            max_daily = limits.get("max_daily")
            min_daily = limits.get("min_daily")
            max_serve = limits.get("max_serve")
            unit = limits.get("unit", "mg")

            status = "PASS"
            details = "Compliant under FSANZ Schedule 29"

            if compound == "Caffeine":
                if serve_val > 0:
                    warnings.add(MANDATORY_WARNINGS["caffeine"])
                if max_serve and serve_val > max_serve:
                    status = "FAIL"
                    details = f"Exceeds max single serve cap ({max_serve} mg/serve)."
                    overall_status = "FAIL"
                elif max_daily and daily_val > max_daily:
                    status = "FAIL"
                    details = f"Exceeds max daily cap ({max_daily} mg/day)."
                    overall_status = "FAIL"

            elif max_daily and daily_val > max_daily:
                status = "FAIL"
                details = f"Exceeds FSANZ Schedule 29 daily cap ({max_daily} {unit})."
                overall_status = "FAIL"

            elif min_daily and daily_val < min_daily:
                status = "WARNING"
                details = f"Below minimum recommended daily sports intake ({min_daily} {unit})."
                if overall_status != "FAIL":
                    overall_status = "WARNING"

            audit_table.append({
                "Compound": compound,
                "Per Serve": f"{serve_val:.2f} {unit}",
                "Daily Intake": f"{daily_val:.2f} {unit}",
                "Regulatory Limit": f"Max {max_daily} {unit}/day" if max_daily else "Uncapped",
                "Status": status,
                "Details": details
            })

        # 4. Non-Ideal Solution Osmolality Engine
        total_osmoles = sum(
            (ing.amount_per_serve_mg / 1000.0 / ing.mw) * ing.van_thoff 
            for ing in inputs["ingredients"] if ing.amount_per_serve_mg > 0
        )
        osmolality = (total_osmoles / dilution_l) * 0.93 * 1000.0

        if osmolality < 270.0:
            osmo_classification = "Hypotonic (Rapid Fluid Absorption)"
        elif osmolality > 330.0:
            osmo_classification = "Hypertonic (Slowed Gastric Emptying)"
        else:
            osmo_classification = "Isotonic (Optimal Fluid/Electrolyte Balance)"

        return {
            "product_name": inputs["product_name"],
            "flavor": inputs["flavor"],
            "stick_weight_g": inputs["stick_weight"],
            "serves_per_day": serves,
            "overall_status": overall_status,
            "sodium_mmol_l": sodium_mmol_l,
            "audit_table": audit_table,
            "osmolality_mOsm_kg": round(osmolality, 2),
            "osmo_classification": osmo_classification,
            "mandatory_warnings": list(warnings)
        }
